#ifndef ZEITERFASSUNGLIB_GLOBAL_H
#define ZEITERFASSUNGLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ZEITERFASSUNGLIB_LIBRARY)
#  define ZEITERFASSUNGLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ZEITERFASSUNGLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ZEITERFASSUNGLIB_GLOBAL_H
