#pragma once

#include <QtGlobal>

#if defined(ZEITERFASSUNGCORELIB_LIBRARY)
#  define ZEITERFASSUNGCORELIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ZEITERFASSUNGCORELIBSHARED_EXPORT Q_DECL_IMPORT
#endif
